name: Produce data from CSV
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: raw-documents-a
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
