name: Create embeddings
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw-documents-v1
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: embeddings-sbert
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
