name: Starter source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: hello-world-source
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
